name: Update Databricks Repo on Push

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI (curl)
        run: |
          set -euxo pipefail
          # Install latest from 'main'. To pin, replace 'main' with a tag like 'v0.265.0'.
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          # Ensure PATH includes the CLI install location (usually ~/.local/bin)
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          databricks -v

      - name: Configure Databricks CLI
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_URL }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}

      - name: Update Repo Branch
        run: |
          databricks repos update ${{ secrets.REPO }} --branch ${{ secrets.BRANCH_NAME }}
