name: Update Databricks Repo on Push

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest
    # Make creds available to every step in this job
    env:
      # Must include the scheme and no trailing slash, e.g. https://adb-1234567890123456.7.azuredatabricks.net
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_URL }}
      # A PAT with workspace scope
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI (curl)
        run: |
          set -euxo pipefail
          # Install latest from 'main'. To pin, replace 'main' with a tag like 'v0.265.0'.
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          # Ensure PATH includes the CLI install location (usually ~/.l

      # - name: Configure Databricks CLI
      #   run: |
      #     export DATABRICKS_HOST=${{ secrets.DATABRICKS_URL }}
      #     export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}
          
      - name: Update git repo
        run: |
          databricks repos update /Workspace/hv_db1 --branch main

      - name: job creation
        run: |
          databricks jobs create --json jobs.json
      
