name: Update Databricks Repo on Push

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI (curl)
        run: |
          set -euxo pipefail
          # Install latest from 'main'. To pin, replace 'main' with a tag like 'v0.265.0'.
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          # Ensure PATH includes the CLI install location (usually ~/.l
          
      - name: Update git repo
        run: |
          databricks repos update /Workspace/hv_db1 --branch main
      
